import type { CatalogSet } from "./catalog";

// Generated once from the public TCGdex set directory. These are descriptive
// machine translations, not official localized product names. The captured
// source name prevents a stale translation from being shown after an upstream correction.
const automaticEnglishSetNames: Readonly<Record<string, readonly [sourceName: string, englishName: string]>> = {
  "tdx-ja-set-ADV1": ["拡張パック", "Expansion Packs"],
  "tdx-ja-set-ADV2": ["砂漠のきせき", "Desert Kiseki"],
  "tdx-ja-set-ADV3": ["天空の覇者", "Celestial Overlord"],
  "tdx-ja-set-ADV4": ["強化拡張パックex1マグマVSアクア ふたつの野望", "Enhanced Expansion Pack ex1 Magma vs Aqua Two Ambitions"],
  "tdx-ja-set-ADV5": ["とかれた封印", "Orchestrated Seal"],
  "tdx-ja-set-CP1": ["マグマ団VSアクア団 ダブルクライシス", "Magma Group vs Aqua Group Double Crisis"],
  "tdx-ja-set-CP2": ["伝説キラコレクション", "Legendary Kira Collection"],
  "tdx-ja-set-CP3": ["ポケキュンコレクション", "Poke Kun Collection"],
  "tdx-ja-set-CP4": ["プレミアムチャンピオンパック EX×M×BREAK", "Premium champion pack EX × M × break"],
  "tdx-ja-set-CP5": ["冷酷の反逆者", "Ruthless Renegade"],
  "tdx-ja-set-CP6": ["ポケットモンスターカードゲーム 拡張パック 20th Anniversary", "Pokemon Card Game Expansion Pack 20th Anniversary"],
  "tdx-ja-set-CS1.5": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-CS1a": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-CS1b": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-CS2.5": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-CS2a": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-CS2b": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-CS3.5": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-CS3a": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-CS3b": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-CS3D": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-CS4": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-CS4a": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-CS4b": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-CS4Da": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-CSA": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-E1": ["基本拡張パック", "Basic Expansion Pack"],
  "tdx-ja-set-E2": ["地図にない町", "Town not on map"],
  "tdx-ja-set-E3": ["海からの風", "Wind from the sea"],
  "tdx-ja-set-E4": ["裂けた大地", "Torn Earth"],
  "tdx-ja-set-E5": ["神秘なる山", "Mysterious Mountain"],
  "tdx-ja-set-L1a": ["ハートゴールドコレクション", "Heart gold collection"],
  "tdx-ja-set-L1b": ["ソウルシルバーコレクション", "Soul silver collection"],
  "tdx-ja-set-L2": ["よみがえる伝説", "The Legend of Yomiga"],
  "tdx-ja-set-L3": ["頂上大激突", "Apex Collision"],
  "tdx-ja-set-LL": ["強化パック ロストリンク", "Enhanced Pack Lost Link"],
  "tdx-ja-set-M-P": ["メガ プロモカード", "Mega Promo Card"],
  "tdx-ja-set-M1L": ["メガブレイブ", "Mega Brave"],
  "tdx-ja-set-M1S": ["メガシンフォニア", "Mega Sinfonia"],
  "tdx-ja-set-M2": ["インフェルノX", "Inferno X"],
  "tdx-ja-set-M2a": ["MEGAドリームex", "Mega dream ex"],
  "tdx-ja-set-M3": ["ムニキスゼロ", "Munikis Zero"],
  "tdx-ja-set-M4": ["ニンジャスピナー", "Ninja Spinner"],
  "tdx-ja-set-M5": ["アビスアイ", "Abyss Eye"],
  "tdx-ja-set-MC": ["スタートデッキ100 バトルコレクション", "Start Deck 100 Battle Collection"],
  "tdx-ja-set-neo1": ["金、銀、新世界へ...", "Gold, silver, new worlds..."],
  "tdx-ja-set-neo2": ["遺跡をこえて...", "Beyond the ruins..."],
  "tdx-ja-set-neo3": ["めざめる伝説", "Awakening Legend"],
  "tdx-ja-set-neo4": ["闇、そして光へ...", "Into darkness and light..."],
  "tdx-ja-set-PCG1": ["伝説の飛翔", "Legendary Flight"],
  "tdx-ja-set-PCG10": ["ワールドチャンピオンズパック", "World Champions Pack"],
  "tdx-ja-set-PCG2": ["蒼空の激突", "Blue Skies Collide"],
  "tdx-ja-set-PCG3": ["ロケット団の逆襲", "Rocket Squad Strikes Back"],
  "tdx-ja-set-PCG4": ["金の空、銀の海", "Gold sky, silver sea"],
  "tdx-ja-set-PCG5": ["まぼろしの森", "Maboroshi no Mori"],
  "tdx-ja-set-PCG6": ["ホロンの研究塔", "Holon Research Tower"],
  "tdx-ja-set-PCG7": ["ホロンの幻影", "Holon's Apparition"],
  "tdx-ja-set-PCG8": ["きせきの結晶", "Kiseki Crystals"],
  "tdx-ja-set-PCG9": ["さいはての攻防", "Saihate offense and defense"],
  "tdx-ja-set-PMCG1": ["拡張パック", "Expansion Packs"],
  "tdx-ja-set-PMCG2": ["ポケモンジャングル", "Pokémon Jungle"],
  "tdx-ja-set-PMCG3": ["化石の秘密", "Fossil Secrets"],
  "tdx-ja-set-PMCG4": ["ロケット団", "Rocket Squadron"],
  "tdx-ja-set-PMCG5": ["リーダーズスタジアム", "Leaders Stadium"],
  "tdx-ja-set-PMCG6": ["闇からの挑戦", "A Challenge from the Darkness"],
  "tdx-ja-set-S10a": ["ダークファンタズマ", "Dark Phantasm"],
  "tdx-ja-set-S10D": ["タイムゲイザー", "Time Gazer"],
  "tdx-ja-set-S10P": ["スペースジャグラー", "Space Juggler"],
  "tdx-ja-set-S11": ["ロストアビス", "Lost Avis"],
  "tdx-ja-set-S11a": ["白熱のアルカナ", "Glowing Arcana"],
  "tdx-ja-set-S12": ["パラダイムトリガー", "Paradigm Trigger"],
  "tdx-ja-set-S12a": ["VSTARユニバース", "VSTAR Universe"],
  "tdx-ja-set-S1a": ["VMAXライジング", "Vmax Rising"],
  "tdx-ja-set-S1H": ["シールド", "Shield"],
  "tdx-ja-set-S1W": ["ソード", "Sword"],
  "tdx-ja-set-S2": ["反逆クラッシュ", "Mutiny Crash"],
  "tdx-ja-set-S2a": ["爆炎ウォーカー", "Explosive Walkers"],
  "tdx-ja-set-S3": ["ムゲンゾーン", "Mugenzone"],
  "tdx-ja-set-S3a": ["伝説の鼓動", "Legendary Pulse"],
  "tdx-ja-set-S4": ["仰天のボルテッカー", "Astounding Vorteker"],
  "tdx-ja-set-S4a": ["シャイニースターV", "Shiny Star V"],
  "tdx-ja-set-S5a": ["双璧のファイター", "Two-Walled Fighter"],
  "tdx-ja-set-S5I": ["一撃マスター", "Strike Mastery"],
  "tdx-ja-set-S5R": ["連撃マスター", "Combo Mastery"],
  "tdx-ja-set-S6a": ["イーブイヒーローズ", "Eeeee Heroes"],
  "tdx-ja-set-S6H": ["白銀のランス", "Lance of Silver"],
  "tdx-ja-set-S6K": ["漆黒のガイスト", "Jet-black Geist"],
  "tdx-ja-set-S7D": ["摩天パーフェクト", "Skyscraper Perfect"],
  "tdx-ja-set-S7R": ["蒼空ストリーム", "Azure Stream"],
  "tdx-ja-set-S8": ["フュージョンアーツ", "Fusion Arts"],
  "tdx-ja-set-S8a": ["25th アニバーサリーコレクション", "25th anniversary collection"],
  "tdx-ja-set-S8b": ["VMAXクライマックス", "Vmax climax"],
  "tdx-ja-set-S9": ["スターバース", "Starburst"],
  "tdx-ja-set-S9a": ["バトルリージョン", "Battle Region"],
  "tdx-ja-set-SM0": ["ピカチュウと新しい仲間たち", "Pikachu and his new friends"],
  "tdx-ja-set-SM1+": ["サン＆ムーン", "Sun & Moon"],
  "tdx-ja-set-SM10": ["ダブルブレイズ", "Double Blaze"],
  "tdx-ja-set-SM10a": ["ジージーエンド", "Gigi End"],
  "tdx-ja-set-SM10b": ["スカイレジェンド", "Sky Legend"],
  "tdx-ja-set-SM11": ["ミラクルツイン", "Miracle Twin"],
  "tdx-ja-set-SM11a": ["リミックスバウト", "Remix Bout"],
  "tdx-ja-set-SM11b": ["ドリームリーグ", "Dream League"],
  "tdx-ja-set-SM12": ["オルタージェネシス", "Alter Genesis"],
  "tdx-ja-set-SM12a": ["TAG TEAM GX タッグオールスターズ", "Tag team GX Tag All Stars"],
  "tdx-ja-set-SM1M": ["コレクションムーン", "Collection Moon"],
  "tdx-ja-set-SM1p": ["サン＆ムーン", "Sun & Moon"],
  "tdx-ja-set-SM1S": ["コレクションサン", "Collection Sun"],
  "tdx-ja-set-sm2+": ["新たなる試練の向こう", "Beyond new challenges"],
  "tdx-ja-set-SM2K": ["キミを待つ島々", "Islands waiting for you"],
  "tdx-ja-set-SM2L": ["アローラの月光", "Alora's Moonlight"],
  "tdx-ja-set-SM2p": ["新たなる試練の向こう", "Beyond new challenges"],
  "tdx-ja-set-SM3+": ["ひかる伝説", "Legend of Hikaru"],
  "tdx-ja-set-SM3H": ["闘う虹を見たか", "Did you see the fighting rainbow?"],
  "tdx-ja-set-SM3N": ["光を喰らう闇", "Darkness that eats light"],
  "tdx-ja-set-SM3p": ["ひかる伝説", "Legend of Hikaru"],
  "tdx-ja-set-SM4+": ["GXバトルブースト", "GX Battle Boost"],
  "tdx-ja-set-SM4A": ["超次元の暴獣", "Ultra-Dimensional Violent Beast"],
  "tdx-ja-set-SM4p": ["GXバトルブースト", "GX Battle Boost"],
  "tdx-ja-set-SM4S": ["覚醒の勇者", "Awakening Hero"],
  "tdx-ja-set-SM5+": ["ウルトラフォース", "Ultra Force"],
  "tdx-ja-set-SM5M": ["ウルトラムーン", "Ultra Moon"],
  "tdx-ja-set-SM5p": ["ウルトラフォース", "Ultra Force"],
  "tdx-ja-set-SM5S": ["ウルトラサン", "Ultra Sun"],
  "tdx-ja-set-SM6": ["禁断の光", "Forbidden Light"],
  "tdx-ja-set-SM6a": ["ドラゴンストーム", "Dragonstorm"],
  "tdx-ja-set-SM6b": ["チャンピオンロード", "Champion Road"],
  "tdx-ja-set-SM7": ["裂空のカリスマ", "Charisma in the Splitting Sky"],
  "tdx-ja-set-SM7a": ["迅雷スパーク", "Thunderbolt Spark"],
  "tdx-ja-set-SM7b": ["フェアリーライズ", "Fairy Rise"],
  "tdx-ja-set-SM8": ["超爆インパクト", "Explosive Impact"],
  "tdx-ja-set-SM8a": ["ダークオーダー", "Dark Order"],
  "tdx-ja-set-SM8b": ["GXウルトラシャイニー", "GX Ultra Shiny"],
  "tdx-ja-set-SM9": ["タッグボルト", "Tag Bolt"],
  "tdx-ja-set-SM9a": ["ナイトユニゾン", "Night Unison"],
  "tdx-ja-set-SM9b": ["フルメタルウォール", "Full Metal Wall"],
  "tdx-ja-set-SMP2": ["名探偵ピカチュウ", "Detective Pikachu"],
  "tdx-ja-set-SV-P": ["スカーレット&バイオレット プロモカード", "Scarlet & Violet Promo Card"],
  "tdx-ja-set-SV10": ["ロケット団の栄光", "The Glory of the Rocket Company"],
  "tdx-ja-set-SV11B": ["ブラックボルト", "Black Bolt"],
  "tdx-ja-set-SV11W": ["ホワイトフレア", "White Flare"],
  "tdx-ja-set-SV1a": ["トリプレットビート", "Triplet Beat"],
  "tdx-ja-set-SV1S": ["スカーレットex", "Scarlet ex"],
  "tdx-ja-set-SV1V": ["バイオレットex", "Violet ex"],
  "tdx-ja-set-SV2a": ["ポケモンカード151", "Pokémon Card 151"],
  "tdx-ja-set-SV2D": ["クレイバースト", "Clay Burst"],
  "tdx-ja-set-SV2P": ["スノーハザード", "Snow Hazard"],
  "tdx-ja-set-SV3": ["黒炎の支配者", "Ruler of the Black Flame"],
  "tdx-ja-set-SV3a": ["レイジングサーフ", "Raging Surf"],
  "tdx-ja-set-SV4a": ["レイジングサーフ", "Raging Surf"],
  "tdx-ja-set-SV4K": ["古代の咆哮", "Ancient Roar"],
  "tdx-ja-set-SV4M": ["未来の一閃", "Future Flash"],
  "tdx-ja-set-SV5a": ["クリムゾンヘイズ", "Crimson Haze"],
  "tdx-ja-set-SV5K": ["ワイルドフォース", "Wild Force"],
  "tdx-ja-set-SV5M": ["サイバージャッジ", "Cyber Judge"],
  "tdx-ja-set-SV6": ["変幻の仮面", "Mask of Change"],
  "tdx-ja-set-SV6a": ["ナイトワンダラー", "Night Wanderer"],
  "tdx-ja-set-SV7": ["ステラミラクル", "Stella Miracle"],
  "tdx-ja-set-SV7a": ["楽園ドラゴーナ", "Paradise Dragona"],
  "tdx-ja-set-SV8": ["超電ブレイカー", "Ultra-electric Breaker"],
  "tdx-ja-set-SV8a": ["テラスタルフェスex", "Terra Tal Fest Ex."],
  "tdx-ja-set-SV9": ["バトルパートナーズ", "Battle Partners"],
  "tdx-ja-set-SV9a": ["熱風のアリーナ", "Hot Air Arena"],
  "tdx-ja-set-SVK": ["デッキビルドBOX ステラミラクル", "Deck Build Box Stella Miracle"],
  "tdx-ja-set-SVLN": ["スターターセット テラスタイプ：ステラ ニンフィアex", "Starter Set Terrace Type: Stella Nymphia ex"],
  "tdx-ja-set-SVLS": ["スターターセット テラスタイプ：ステラ ソウブレイズex", "Starter Set Terrace Type: Stella Saw Blaze ex"],
  "tdx-ja-set-VS1": ["ポケモンカード★VS", "Pokémon cards★ vs."],
  "tdx-ja-set-web1": ["ポケモンカード★web", "pokemon card★ web"],
  "tdx-ja-set-XY10": ["めざめる超王", "Aiming Super King"],
  "tdx-ja-set-XY11a": ["爆熱の闘士", "Fiery Fighter"],
  "tdx-ja-set-XY11b": ["冷酷の反逆者", "Ruthless Renegade"],
  "tdx-ja-set-XY1a": ["コレクションX", "Collection X"],
  "tdx-ja-set-XY1b": ["コレクションY", "Collection Y"],
  "tdx-ja-set-XY2": ["ワイルドブレイズ", "Wild Blaze"],
  "tdx-ja-set-XY3": ["ライジングフィスト", "Rising Fist"],
  "tdx-ja-set-XY4": ["ファントムゲート", "Phantom Gate"],
  "tdx-ja-set-XY5a": ["ガイアボルケーノ", "Gaia Volcano"],
  "tdx-ja-set-XY5b": ["タイダルストーム", "Tidal Storm"],
  "tdx-ja-set-XY6": ["エメラルドブレイク", "Emerald Break"],
  "tdx-ja-set-XY7": ["バンデットリング", "Bandet Ring"],
  "tdx-ja-set-XY8a": ["青い衝撃", "Blue Shock"],
  "tdx-ja-set-XY8b": ["赤い閃光", "Red Flash"],
  "tdx-ja-set-XY9": ["破天の怒り", "Heaven Shattering Wrath"],
  "tdx-ko-set-CS1.5": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-CS1a": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-CS1b": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-CS2.5": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-CS2a": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-CS2b": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-CS3.5": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-CS3a": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-CS3b": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-CS3D": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-CS4": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-CS4a": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-CS4b": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-CS4Da": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-CSA": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-S10a": ["다크판타스마", "Dark Pantasma"],
  "tdx-ko-set-S10D": ["타임게이저", "Time Gazer"],
  "tdx-ko-set-S10P": ["스페이스저글러", "Spacejuggler"],
  "tdx-ko-set-S11": ["트리플렛비트", "Triplet Bit"],
  "tdx-ko-set-S11a": ["백열의 아르카나", "Glowing arcana"],
  "tdx-ko-set-S12": ["패러다임트리거", "Paradigm Trigger"],
  "tdx-ko-set-S12a": ["VSTAR 유니버스", "VSTAR Universe"],
  "tdx-ko-set-S1a": ["VMAX라이징", "Vmax Rising"],
  "tdx-ko-set-S1H": ["실드", "Shield"],
  "tdx-ko-set-S1W": ["소드", "Sword"],
  "tdx-ko-set-S2": ["반역크래시", "Treason Crash"],
  "tdx-ko-set-S2a": ["폭염워커", "Heatwave Walker"],
  "tdx-ko-set-S3": ["무한존", "Infinite Zone"],
  "tdx-ko-set-S3a": ["전설의 고동", "Legendary Pulse"],
  "tdx-ko-set-S4": ["앙천의 볼트태클", "Angcheon bolt tackle"],
  "tdx-ko-set-S4a": ["샤이니스타V", "SHINISTA V"],
  "tdx-ko-set-S5a": ["쌍벽의 파이터", "Fighter of the Twin Walls"],
  "tdx-ko-set-S5I": ["일격마스터", "Strike Master"],
  "tdx-ko-set-S5R": ["연격마스터", "Clashing Master"],
  "tdx-ko-set-S6a": ["이브이 히어로즈", "Yves Heroes"],
  "tdx-ko-set-S6H": ["백은의 랜스", "Baek Eun's Lance"],
  "tdx-ko-set-S6K": ["칠흑의 가이스트", "The Dark Geist"],
  "tdx-ko-set-S7D": ["마천퍼펙트", "Skyscraper Perfect"],
  "tdx-ko-set-S7R": ["창공의스트림", "Stream of the Sky"],
  "tdx-ko-set-S8": ["퓨전아츠", "Fusion Arts"],
  "tdx-ko-set-S8b": ["VMAX 클라이맥스", "Vmax climax"],
  "tdx-ko-set-S9": ["스타버스", "Starbus"],
  "tdx-ko-set-S9a": ["배틀리전", "Battle League"],
  "tdx-ko-set-SM1+": ["썬&문", "Sun & Moon"],
  "tdx-ko-set-SM10": ["더블블레이즈", "Double Blaze"],
  "tdx-ko-set-SM10a": ["GG엔드", "GG End"],
  "tdx-ko-set-SM10b": ["스카이레전드", "Skylegend"],
  "tdx-ko-set-SM11": ["미라클트윈", "Miracle Twin"],
  "tdx-ko-set-SM11a": ["리믹스바우트", "Remixbout"],
  "tdx-ko-set-SM11b": ["드림리그", "Dream League"],
  "tdx-ko-set-SM12": ["얼터제네시스", "Alter Genesis"],
  "tdx-ko-set-SM12a": ["TAG TEAM GX 태그올스타즈", "Tag team GX Tag All Stars"],
  "tdx-ko-set-SM1M": ["문 컬렉션", "Moon Collection"],
  "tdx-ko-set-SM1S": ["썬 컬렉션", "Sun Collection"],
  "tdx-ko-set-SM2K": ["알로라의 햇빛", "Alora Sunlight"],
  "tdx-ko-set-SM2L": ["알로라의 달빛", "Moonlight of Alola"],
  "tdx-ko-set-SM3+": ["빛나는 전설", "Shining Legend"],
  "tdx-ko-set-SM3H": ["어둠을 밝힌 무지개", "Rainbows lit up by darkness"],
  "tdx-ko-set-SM3N": ["빛을 삼킨 어둠", "Darkness swallowed by light"],
  "tdx-ko-set-SM4+": ["GX 배틀부스트", "GX Battle Boost"],
  "tdx-ko-set-SM4A": ["초차원의 침략자", "Super Dimensional Invaders"],
  "tdx-ko-set-SM4S": ["각성의 용사", "Awakened Warrior"],
  "tdx-ko-set-SM5+": ["울트라포스", "Ultraforce"],
  "tdx-ko-set-SM5M": ["울트라문", "Ultramoon"],
  "tdx-ko-set-SM5S": ["울트라썬", "Ultrasun"],
  "tdx-ko-set-SM6": ["금단의 빛", "Forbidden Light"],
  "tdx-ko-set-SM6a": ["드래곤스톰", "Dragonstorm"],
  "tdx-ko-set-SM6b": ["챔피언로드", "Champion Road"],
  "tdx-ko-set-SM7": ["창공의 카리스마", "Charisma in the Sky"],
  "tdx-ko-set-SM7a": ["플라스마 스파크", "Plasma Spark"],
  "tdx-ko-set-SM7b": ["페어리라이즈", "Fairy Rise"],
  "tdx-ko-set-SM8": ["버스트임팩트", "Burst Impact"],
  "tdx-ko-set-SM8a": ["다크오더", "Dark order"],
  "tdx-ko-set-SM8b": ["GX 울트라샤이니 ULTIMATE", "GX ultra shiny ultimate"],
  "tdx-ko-set-SM9": ["태그볼트", "Tagbolt"],
  "tdx-ko-set-SM9a": ["나이트유니슨", "Night Unison"],
  "tdx-ko-set-SM9b": ["풀메탈월", "Full metal wall"],
  "tdx-ko-set-SMP2": ["명탐정 피카츄", "Detective Pikachu"],
  "tdx-ko-set-SV1a": ["트리플렛비트", "Triplet Beat"],
  "tdx-ko-set-SV1S": ["스칼렛ex", "Scarlet ex"],
  "tdx-ko-set-SV1V": ["바이올렛ex", "Violetex"],
  "tdx-ko-set-SV2a": ["포켓몬 카드 151", "Pokemon Card 151"],
  "tdx-ko-set-SV2D": ["클레이버스트", "Clay Burst"],
  "tdx-ko-set-SV2P": ["스노해저드", "Snow Hazard"],
  "tdx-ko-set-SV3": ["흑염의 지배자", "Ruler of the Black Flame"],
  "tdx-ko-set-SV3a": ["레이징서프", "Raging Surf"],
  "tdx-ko-set-SV4a": ["샤이니트레저 ex", "Shiny Treasure ex"],
  "tdx-ko-set-SV4K": ["고대의 포효", "Ancient Roar"],
  "tdx-ko-set-SV4M": ["미래의 일섬", "Future Flash"],
  "tdx-ko-set-SV5a": ["크림슨헤이즈", "Crimson Haze"],
  "tdx-ko-set-SV5K": ["와일드포스", "Wild Force"],
  "tdx-ko-set-SV5M": ["사이버저지", "Cyber Judge"],
  "tdx-ko-set-SV6": ["변환의 가면", "Mask of Change"],
  "tdx-zh-cn-set-CBB2C": ["宝石包Vol.2", "Gem Pack Vol. 2"],
  "tdx-zh-cn-set-CBB3C": ["宝石包Vol.3", "Gem Pack Vol.3"],
  "tdx-zh-cn-set-CBB4C": ["宝石包 Vol.4", "Gem Pack Vol. 4"],
  "tdx-zh-cn-set-CBB5C": ["宝石包 Vol.5", "Gem Pack Vol.5"],
  "tdx-zh-cn-set-CS1.5C": ["极巨攻防", "Extreme Attack and Defense"],
  "tdx-zh-cn-set-CS1aC": ["横空出世 赫", "Emerging from the sky"],
  "tdx-zh-cn-set-CS1bC": ["极巨争锋 焰", "Extreme Fighting Flame"],
  "tdx-zh-cn-set-CS2.5C": ["璀璨反击", "Brilliant Counter Strike"],
  "tdx-zh-cn-set-CS2aC": ["浓墨重彩 黎", "Ink heavy color Li"],
  "tdx-zh-cn-set-CS2bC": ["浓墨重彩 靛", "Heavy Ink Indigo"],
  "tdx-zh-cn-set-CS3.5C": ["怒炎灼天", "Angry Scorching Heavens"],
  "tdx-zh-cn-set-CS3aC": ["洪荒演武 茂", "Flood performs Wumao"],
  "tdx-zh-cn-set-CS3bC": ["洪荒演武 激", "Flooding and violence"],
  "tdx-zh-cn-set-CS4.5C": ["终末炎舞", "Final Flame Dance"],
  "tdx-zh-cn-set-CS4aC": ["九彩汇聚 朋", "Nine-colored Gathering Peng"],
  "tdx-zh-cn-set-CS4bC": ["九彩汇聚 源", "Nine-colored convergence source"],
  "tdx-zh-cn-set-CS5.5C": ["暗影夺辉", "Shadows take the brilliance"],
  "tdx-zh-cn-set-CS5aC": ["勇魅群星 魅", "Brave Star Charm"],
  "tdx-zh-cn-set-CS5bC": ["勇魅群星 勇", "Brave Charms Stars Brave"],
  "tdx-zh-cn-set-CS6.5C": ["胜象星引", "Victorious Star Citation"],
  "tdx-zh-cn-set-CS6aC": ["碧海暗影 啸", "Blue Sea Shadow Howl"],
  "tdx-zh-cn-set-CS6bC": ["碧海暗影 逐", "Blue Sea Shadow Chasing"],
  "tdx-zh-cn-set-csm1.5": ["战斗精英", "Battle Elite"],
  "tdx-zh-cn-set-CSM1.5C": ["对战精英", "Battle Elite"],
  "tdx-zh-cn-set-csm1a": ["风暴涌现", "Storm surge"],
  "tdx-zh-cn-set-CSM1aC": ["横空出世 赫", "Emerging from the sky"],
  "tdx-zh-cn-set-csm1b": ["风暴涌现", "Storm surge"],
  "tdx-zh-cn-set-CSM1bC": ["横空出世 苍", "Born horizontally in the sky"],
  "tdx-zh-cn-set-csm1c": ["风暴涌现", "Storm surge"],
  "tdx-zh-cn-set-CSM1cC": ["横空出世 泽", "Born Horizontally"],
  "tdx-zh-cn-set-csm2.5": ["精彩的比赛", "Wonderful match"],
  "tdx-zh-cn-set-CSM2.5C": ["炫奇争胜", "Stunning Struggle"],
  "tdx-zh-cn-set-csm2a": ["闪耀协同效应", "Shining Synergy"],
  "tdx-zh-cn-set-CSM2aC": ["交相辉映 沐", "Intersecting Glowing Reflection"],
  "tdx-zh-cn-set-csm2b": ["闪耀协同效应", "Shining Synergy"],
  "tdx-zh-cn-set-CSM2bC": ["交相辉映 魁", "Intersecting and shining"],
  "tdx-zh-cn-set-csm2c": ["闪耀协同效应", "Shining Synergy"],
  "tdx-zh-cn-set-CSM2cC": ["交相辉映 唤", "intersecting glowing call"],
  "tdx-zh-cn-set-CSMPiC": ["对战派对组合 奖励包", "Battle Party Combo Reward Pack"],
  "tdx-zh-cn-set-CSV1C": ["宝石包 第一卷", "Gem Pack Volume 1"],
  "tdx-zh-cn-set-CSV2C": ["奇迹启程", "Miracle Departure"],
  "tdx-zh-cn-set-CSV3C": ["无畏太晶", "Dreadnought crystal"],
  "tdx-zh-cn-set-CSV4C": ["嘉奖回合", "Commendation Round"],
  "tdx-zh-cn-set-CSV5C": ["黑晶炽诚", "Black Crystal Sincerity"],
  "tdx-zh-cn-set-CSV6C": ["真实玄虚", "True Mysterious Void"],
  "tdx-zh-cn-set-CSV7C": ["利刃猛醒", "Sharp sword awakens"],
  "tdx-zh-cn-set-CSV8C": ["璀璨诡幻", "Brilliant and fantastic"],
  "tdx-zh-cn-set-CSV9.5C": ["太晶盛聚", "Taijing Shengju"],
  "tdx-zh-cn-set-CSV9C": ["星彩晶璃", "Star crystal"],
  "tdx-zh-cn-set-SV10": ["火箭隊的榮耀", "The Glory of the Rockets"],
  "tdx-zh-cn-set-SV7": ["星晶奇跡", "Miracle of Star Crystals"],
  "tdx-zh-cn-set-SV7a": ["樂園騰龍", "Paradise Tenglong"],
  "tdx-zh-cn-set-SV8": ["超電突圍", "Ultra-electric breakout"],
  "tdx-zh-cn-set-SV8a": ["太晶慶典ex", "Taijing Celebration ex"],
  "tdx-zh-cn-set-SV9": ["對戰搭檔", "Matchmaking Partners"],
  "tdx-zh-cn-set-SV9a": ["熱風競技場", "Hot Air Arena"],
  "tdx-zh-tw-set-CS1.5": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-CS1a": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-CS1b": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-CS2.5": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-CS2a": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-CS2b": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-CS3.5": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-CS3a": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-CS3b": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-CS3D": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-CS4": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-CS4a": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-CS4b": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-CS4Da": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-CSA": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-S10a": ["黑暗亡靈", "Dark Undead"],
  "tdx-zh-tw-set-S10D": ["時間觀察者", "Time Watcher"],
  "tdx-zh-tw-set-S10P": ["空間魔術師", "Spatial Magician"],
  "tdx-zh-tw-set-S11": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-S11a": ["白熱奧祕", "White Hot Mystery"],
  "tdx-zh-tw-set-S12": ["思維激盪", "Thought Stirrings"],
  "tdx-zh-tw-set-S12a": ["天地萬物VSTAR", "Heaven and Earth Everything VSTAR"],
  "tdx-zh-tw-set-S4": ["驚天伏特攻擊", "Stunning Volt Attacks"],
  "tdx-zh-tw-set-S4a": ["閃色明星V", "Sparkling Star V"],
  "tdx-zh-tw-set-S5a": ["雙璧戰士", "Shuangbi Warrior"],
  "tdx-zh-tw-set-S5I": ["一撃大師", "Master of One Shot"],
  "tdx-zh-tw-set-S5R": ["連撃大師", "Combo Master"],
  "tdx-zh-tw-set-S6a": ["伊布英雄", "Ibrahimovic Heroes"],
  "tdx-zh-tw-set-S6H": ["銀白戰槍", "Silver War Gun"],
  "tdx-zh-tw-set-S6K": ["漆黑幽魂", "Pitch Black Ghost"],
  "tdx-zh-tw-set-S7D": ["摩天巔峰", "Skyscraper Summit"],
  "tdx-zh-tw-set-S7R": ["蒼空烈流", "Sky Rapid"],
  "tdx-zh-tw-set-S8": ["匯流藝術", "The art of convergence"],
  "tdx-zh-tw-set-S8a": ["25週年收藏款", "25th Anniversary Collection"],
  "tdx-zh-tw-set-S8b": ["VMAX絕群壓軸", "Vmax Absolute Finisher"],
  "tdx-zh-tw-set-S9": ["星星誕生", "Star birth"],
  "tdx-zh-tw-set-S9a": ["對戰地區", "Battle Zone"],
  "tdx-zh-tw-set-SC1a": ["劍&盾 SET A", "Sword & shield set A"],
  "tdx-zh-tw-set-SC1b": ["劍&盾 SET B", "Sword & shield set B"],
  "tdx-zh-tw-set-SC1D": ["劍&盾", "Swords & Shields"],
  "tdx-zh-tw-set-SC2a": ["無極力量 SET A", "Limitless Force set A"],
  "tdx-zh-tw-set-SC2b": ["無極力量 SET B", "Limitless Force set B"],
  "tdx-zh-tw-set-SC2D": ["無極力量", "Limitless Power"],
  "tdx-zh-tw-set-SCA": ["搭檔", "Partner"],
  "tdx-zh-tw-set-SCB": ["挑戰", "Challenges"],
  "tdx-zh-tw-set-SCC": ["進化", "Evolution"],
  "tdx-zh-tw-set-SCD": ["強大", "Powerful"],
  "tdx-zh-tw-set-SDL": ["噴火龍", "Spitfire Dragon"],
  "tdx-zh-tw-set-SDM": ["超夢", "Super Dreams"],
  "tdx-zh-tw-set-SDP": ["皮卡丘", "Pikachu"],
  "tdx-zh-tw-set-SH": ["寶可夢卡牌家庭組合", "Pokemon Card Family Set"],
  "tdx-zh-tw-set-SI": ["初階牌組100", "Starter deck 100"],
  "tdx-zh-tw-set-SJ": ["藏瑪然特VS無極汰那", "Hidden Marant VS Infinity Knight"],
  "tdx-zh-tw-set-SK": ["頂級訓練家收藏箱 VSTAR", "Top trainer collection VSTAR"],
  "tdx-zh-tw-set-SLD": ["起始組合VSTAR 達克萊伊", "Starting combo VSTAR da Crai"],
  "tdx-zh-tw-set-SLL": ["起始組合VSTAR 路卡利歐", "Starting combo VSTAR Lucario"],
  "tdx-zh-tw-set-SN": ["初階牌組100 特別版", "Beginner deck 100 special edition"],
  "tdx-zh-tw-set-SP5": ["強大", "Powerful"],
  "tdx-zh-tw-set-SP6": ["VSTAR特別組合", "VSTAR Special Bundle"],
  "tdx-zh-tw-set-SPD": ["VSTAR&VMAX 高級牌組 代歐奇希斯", "VSTAR&VMAX Premium Deck Deochesis"],
  "tdx-zh-tw-set-SPZ": ["VSTAR&VMAX 高級牌組 捷拉奧拉", "VSTAR&VMAX Premium Geraola"],
  "tdx-zh-tw-set-SV-P": ["特典卡 朱&紫", "Boutique Caju & Purple"],
  "tdx-zh-tw-set-SV10": ["火箭隊的榮耀", "The Glory of the Rockets"],
  "tdx-zh-tw-set-SV1a": ["三連音爆", "Triple Sonic Boom"],
  "tdx-zh-tw-set-SV1S": ["朱ex", "Zhu ex"],
  "tdx-zh-tw-set-SV1V": ["紫ex", "Purple ex"],
  "tdx-zh-tw-set-SV2a": ["寶可夢卡牌151", "Pokemon Card 151"],
  "tdx-zh-tw-set-SV2D": ["碟旋暴擊", "Spinning Critical Strike"],
  "tdx-zh-tw-set-SV2P": ["冰雪險境", "Snow and Ice Danger"],
  "tdx-zh-tw-set-SV3": ["黯焰支配者", "Dark Flame Dominator"],
  "tdx-zh-tw-set-SV3a": ["激狂駭浪", "Frenzied Hacking Waves"],
  "tdx-zh-tw-set-SV4a": ["閃色寶藏ex", "Sparkling Treasure ex"],
  "tdx-zh-tw-set-SV4K": ["古代咆哮", "Ancient Roar"],
  "tdx-zh-tw-set-SV4M": ["未來閃光", "Future Sparkle"],
  "tdx-zh-tw-set-SV5a": ["緋紅薄霧", "Crimson Mist"],
  "tdx-zh-tw-set-SV5K": ["狂野之力", "Power of the Wild"],
  "tdx-zh-tw-set-SV5M": ["異度審判", "Judgment of Heresy"],
  "tdx-zh-tw-set-SV6": ["變幻假面", "Phantom Mask"],
  "tdx-zh-tw-set-SV6a": ["黑夜漫遊者", "Night Wanderer"],
  "tdx-zh-tw-set-SV7": ["星晶奇跡", "Miracle of Star Crystals"],
  "tdx-zh-tw-set-SV7a": ["樂園騰龍", "Paradise Tenglong"],
  "tdx-zh-tw-set-SV8": ["超電突圍", "Ultra-electric breakout"],
  "tdx-zh-tw-set-SV8a": ["太晶慶典ex", "Taijing Celebration ex"],
  "tdx-zh-tw-set-SV9": ["對戰搭檔", "Matchmaking Partners"],
  "tdx-zh-tw-set-SV9a": ["熱風競技場", "Hot Air Arena"],
  "tdx-zh-tw-set-SVAL": ["起始組合ex 呆火鱷&電龍 ex", "Starting combo ex Vigilante & Dragon ex"],
  "tdx-zh-tw-set-SVAM": ["起始組合ex 新葉喵&路卡利歐 ex", "Starting Combination ex New Leaf Meow & Lucario ex"],
  "tdx-zh-tw-set-SVAW": ["起始組合ex 潤水鴨&謎擬Ｑ ex", "Starting Combination ex Watering Duck & Mystery Q ex"],
  "tdx-zh-tw-set-SVB": ["頂級訓練家收藏箱ex", "Top trainer collection ex"],
  "tdx-zh-tw-set-SVC": ["皮卡丘特別組合", "Pikachu Special Combo"],
  "tdx-zh-tw-set-SVD": ["ex初階牌組", "ex Beginner deck"],
  "tdx-zh-tw-set-SVEL": ["骨紋巨聲鱷ex", "Bone Line Gigantosuchus ex"],
  "tdx-zh-tw-set-SVEM": ["超夢ex", "Super Dreams ex"],
  "tdx-zh-tw-set-SVF": ["黯焰支配者", "Dark Flame Dominator"],
  "tdx-zh-tw-set-SVHK": ["未來密勒頓ex", "Future Millerton ex"],
  "tdx-zh-tw-set-SVHM": ["閃色寶藏ex", "Sparkling Treasure ex"],
  "tdx-zh-tw-set-SVP1": ["ex特別組合", "ex special combinations"],
};

export function automaticEnglishSetName(set: Pick<CatalogSet, "id" | "language" | "name">) {
  if (set.language === "en") return undefined;
  const translation = automaticEnglishSetNames[set.id];
  if (!translation || translation[0] !== set.name) return undefined;
  const translatedName = translation[1].trim();
  if (!translatedName || translatedName.localeCompare(set.name, undefined, { sensitivity: "accent" }) === 0) return undefined;
  return translatedName;
}
